#!/usr/bin/env bash
#
# Issue #27 (Task 3): install a local pre-commit hook that runs the
# blocking-in-timers lint (supervisor/scripts/lint-blocking-in-timers.ts).
#
# `.git/hooks` is NOT version-controlled, so this committed installer is the
# shareable entry point — run it once after cloning for fast local feedback.
# CI enforces the same lint on every PR regardless of whether this is installed
# (see .github/workflows/ci.yml), so this hook is a convenience, not the gate.
#
# Robust against git worktrees (RW-008) by resolving the hooks dir via
# `git rev-parse --git-path hooks`, which honors core.hooksPath and worktrees.
set -euo pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
# `--git-path hooks` honors core.hooksPath and worktrees, but may return either
# an absolute path or one relative to REPO_ROOT — normalize to absolute.
HOOKS_DIR="$(cd "$REPO_ROOT" && git rev-parse --git-path hooks)"
case "$HOOKS_DIR" in
  /*) : ;;
  *) HOOKS_DIR="$REPO_ROOT/$HOOKS_DIR" ;;
esac
mkdir -p "$HOOKS_DIR"
HOOK="$HOOKS_DIR/pre-commit"
MARKER="claude-hub:install-git-hooks"

if [[ -f "$HOOK" ]] && ! grep -q "$MARKER" "$HOOK" 2>/dev/null; then
  echo "✗ A pre-commit hook already exists and was not generated by this script:" >&2
  echo "    $HOOK" >&2
  echo "  Refusing to overwrite. Merge the lint call manually or remove the file first." >&2
  exit 1
fi

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# claude-hub:install-git-hooks (Issue #27) — auto-generated; edit the installer
# at scripts/install-git-hooks.sh, not this file.
set -euo pipefail
REPO_ROOT="$(git rev-parse --show-toplevel)"
# Only run the lint when supervisor TypeScript sources (including the linter
# itself) are staged (fast path).
if git diff --cached --name-only --diff-filter=ACM | grep -qE '^supervisor/(src|scripts)/.*\.ts$'; then
  if command -v bun >/dev/null 2>&1; then
    ( cd "$REPO_ROOT/supervisor" && bun scripts/lint-blocking-in-timers.ts )
  else
    echo "[pre-commit] bun not found; skipping blocking-in-timers lint (CI still enforces it)." >&2
  fi
fi
EOF

chmod +x "$HOOK"
echo "✓ Installed pre-commit hook → $HOOK"
echo "  It runs supervisor/scripts/lint-blocking-in-timers.ts when supervisor/src/*.ts is staged."
